### ISSUE TITLE
onDisplayedMonthChanged triggers too many callbacks

### ISSUE THREAD

**Issue by sajithu** [ZedTheLed/small_calendar#1]
"onDisplayedMonthChanged" triggers the callback multiple times during a single scroll event. Is there a way to trigger the call back at the end of the scroll event?

**Comment by ZedTheLed** [comment]
I should be able to fix this issue by Wednesday (2018.4.11) and it will require no API changes.

Most likely fix would be to use a [NotificationListener](https://docs.flutter.io/flutter/widgets/NotificationListener-class.html).
I’ll try to to encapsulate PageView inside a NotificationListener and trigger the callback on ScrollEndNotification.

**Comment by sajithu** [comment]
Sounds good. Thanks. Appreciate your great work!
